server:
  port: 8000
spring:
  application:
    name: reg-login-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/yumbo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

